helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/cluster-news
    forcestring: true
  - name: image.tag
    value: main@sha256:58bde745bebaae8ddfc1b8b327be9447abb59ed403aa83f1127c63161da04b96
    forcestring: true
