helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/cluster-news
    forcestring: true
  - name: image.tag
    value: main@sha256:cc1ee0b68e5b0a2c31e547db2ac79887f4c5dc711acde669f815dc1910bd7ad7
    forcestring: true
